### ISSUE TITLE
Future of `signing with smartcard` functionality in dds

### ISSUE THREAD

**Issue by Jyrno42** [sertkeskus/dds-documentation#6]
Since Mobile-ID REST API was announced as a replacement for DigiDocService (atleast for mobile-id) will there be a replacement service for `signing with smartcard` usecase of dds? Or should consumers migrate away from dds smart-card model (by creating the containers themselves).

Context: I am the maintainer of django-esteid where we rely directly on Digidocservice for MID and ID-card signing. For that project we are planning to migrate to Mobile-ID REST API but are wondering what to use for ID-card based signing.

**Comment by jalukse** [comment]
There is no replacement service for _signing with smartcard_ usecase.
Available options are described in https://www.sk.ee/en/News/digidocservice-will-be-replaced-by-the-new-mobile-id-rest-api/

- DigiDoc libraries: [DigiDoc4j ](https://github.com/open-eid/digidoc4j) and [LibDigiDocpp](https://github.com/open-eid/libdigidocpp);
- [Signature Gateway](https://github.com/open-eid/SiGa/wiki) (SiGa) for digital signing;
- [Signature Validation](http://open-eid.github.io/SiVa) (SiVa) service for validating digital signatures.
- [Dokobit.com](https://www.dokobit.com/) and [DigitalMind SigningServices](https://digitalmind.lv/landing/signingservices/)
